### PR TITLE
Fix Component Union

### PR DESCRIPTION
**Pull request by gpoitch**
~~Fixes `MemberComponent` to be a union type instead of an intersection type.~~

Exposes a new type `AnyComponent` that strictly checks components against available types.

### CODE REVIEW

**Comment by gpoitch** [comment]
Unsure on this one.  I think maybe `MemberComponent` may need to be publicly exported as `Component`?

Example:

```ts
const document: AppleNews.ArticleDocument = {
  components: [
      {
        role: 'title',
        text: 'Title'
      },
      ...makeBodyComponents()
    ]
   // ... rest of required fields
}

function makeBodyComponents(): AppleNews.Component[] {
  return [
    {
      role: 'body',
      text: 'body text'
    }
  ]
}
```

Errors:
```
Type '{ role: string; text: string; }' is not assignable to type 'Component'.
  Object literal may only specify known properties, and 'text' does not exist in type 'Component'.
  text: 'body text'

Type 'Component' is not assignable to type 'MemberComponent'.
  Type 'Component' is not assignable to type '{ [key: string]: ComponentFieldValue; }'.
    Index signature is missing in type 'Component'.
   ...makeBodyComponents()
```

**Comment by Robert-Fairley** [comment]
I'm not sure either. I've toyed with implementations for a couple of minutes and I think my reasoning was I wanted to extend the base `Component` definition without going through explicitly defining all possible interface options for a containers children as `Component` only provides fields common to all component implementations.

I'll admit it's a stopgap versus created a giant union type that can be any existing component type.

I don't think setting it to a union type would totally break it, but it would remove the type checking on the common fields.

For instance,

#### Functioning, janky component implementation 
This works
```typescript
class SomeComponent implements Component {
    public role!: string;
    public anchor?: Anchor;
    public animation?: ComponentAnimation;
    public behavior?: Behavior;
    public hidden?: boolean;
    public identifier?: string;
    public layout?: ComponentLayout | string;
    public style?: ComponentStyle | string;

    public text?: string;

    public constructor(data: Component & {[k: string]: any }) {
        this.role = data.role;
        this.anchor = data.anchor;
        this.animation = data.animation;
        this.behavior = data.behavior;
        this.hidden = data.hidden;
        this.identifier = data.identifier;
        this.layout = data.layout;
        this.style = data.style;

        this.text = data.text;
    }
}

const newComponent = new SomeComponent({
    identifier: "boo",
    role: "body",
    text: "Anything",
});
```

##### Non-functioning janky component implementation

```typescript
class SomeComponent implements Component {
    public role!: string;
    public anchor?: Anchor;
    public animation?: ComponentAnimation;
    public behavior?: Behavior;
    public hidden?: boolean;
    public identifier?: string;
    public layout?: ComponentLayout | string;
    public style?: ComponentStyle | string;

    public text?: string;

    public constructor(data: Component | {[k: string]: any }) {
        this.role = data.role;
        this.anchor = data.anchor;
        this.animation = data.animation;
        this.behavior = data.behavior;
        this.hidden = data.hidden;
        this.identifier = data.identifier;
        this.layout = data.layout;
        this.style = data.style;

        this.text = data.text; // This breaks here
    }
}

const newComponent = new SomeComponent({
    identifier: "boo",
    role: "body",
    text: "Anything",
});
```

And breaks with message
```
Property 'text' does not exist on type 'Component | { [k: string]: any; }'.
  Property 'text' does not exist on type 'Component'.ts(2339)
```

--- 

Rather than ad-hoc extending the `Component` type for any children I think I was optimizing for an implementation pattern (though yeah—didn't do _any_ of the work toward it) like below.

Here each child component can be assumed to have the common fields of a `BaseComponent`/`Component` interface but also allow for extension to other component implementations that contain fields that don't exist on the base.

If we were to move from an intersection type to a union type for the `MemberComponent` type, or just move to a `Component` type this implementation would fail:

```typescript
import {
    ComponentFieldValue,
    Container,
    ContainerRoles,
    MemberComponent,
} from "./src/components/article-structure/container";
import { Body } from "./src/components/text/body";

class ContainerClass implements Container {
    public role!: ContainerRoles;
    public components!: MemberComponent[];

    public constructor(data?: Container) {
        if (data) {
            this.role = data.role ? data.role : "container";
            this.components = data.components ? [...data.components] : [];
        } else {
            this.role = "container";
            this.components = [];
        }
    }

    public insertComponent(component: MemberComponent, componentIndex?: number): void {
        if (typeof componentIndex === "number") {
            const tail = this.components.splice(componentIndex);
            const head = [...this.components];
            this.components = [
                ...head,
                component,
                ...tail,
            ];
        } else {
            this.components.push(component);
        }
    }

    public removeComponent(componentIndex: number): void {
        if (
            componentIndex >= this.components.length ||
            componentIndex < 0
            ) {
                throw new Error(`Component does not exist at index ${componentIndex}`);
            }

        delete this.components[componentIndex];
        this.components = this.components.filter((component: MemberComponent | null) => component !== null);
    }
}

class BodyComponent implements Body {
    [key: string ]: ComponentFieldValue;
    public role: "body" = "body";
    public text!: string;

    public constructor(data: Body) {
        this.text = data.text;
    }
}

const newBodyComponent = new BodyComponent({
    role: "body",
    text: "Hello world",
});

const container = new ContainerClass();

container.insertComponent(newBodyComponent);
```

---

Anyway that is all long enough, and I am _completely_ open to suggestions for improving upon that. As far as I can see it might be unavoidable to make a large union type across components, but it might take some refactoring to prevent circular imports. I admit it's been a while since I've been that deep into this library and have only had to use it superficially.

**Comment by Robert-Fairley** [comment]
I suppose another more labourious option would be to start on the implementations and clear up some of these ambiguities and turn the library into one with a proper feature-set for constructing components and articles and make their usage optional...

**Comment by gpoitch** [comment]
@Robert-Fairley thanks for taking a look.  Looking at it again, my PR actually didn't fix the example.

Using the `MemberComponent` type as-is instead of `Component` does fix it.

I admit the architecture is a bit over my head at the moment to offer a proper refactor.

Simply exporting `MemberComponent` for public usage would be my suggestion for the least disruptive solution.  I can update the PR if so.

**Comment by Robert-Fairley** [comment]
I see what you're saying. Sure that seems like it would make sense. There are likely other places throughout the code that similar cases exist.

And I don't blame you! I definitely hit the curb a number of times while pulling this together from the Apple docs. I'll probably give some thought to implementations (at some point) of the components/document/other objects so that vanilla JavaScript projects can take advantage.

**Comment by gpoitch** [comment]
> I'll admit it's a stopgap versus created a giant union type that can be any existing component type.

That seems like a better idea and you'll get the proper types.  Can export this new union of unions type:

```ts
type AnyComponent =
  | Components.Text
  | Components.Images
  | Components.GalleriesAndMosaics
  | Components.SocialMedia
  | Components.Location
  | Components.AudioAndVideo
  | Components.Tables
  | Components.Advertisements
  | Components.AugmentedReality
  | Components.ArticleStructure
```

**Comment by Robert-Fairley** [comment]
Absolutely. If we can successfully somehow reference that type in the `Container` interface then that would be best.

The only gotcha might be a problematic circular reference in that case, but if we can navigate around that then that's the ideal solution.

**Comment by Robert-Fairley** [comment]
Thanks Garth. That looks good to me.

**Pull request merged**
